title: 移動ロボットの制御とROSによる動作計画実習
description: 日本ロボット学会　第113回 ロボットの作り方
theme: jekyll-theme-minimal

repo: "https://github.com/BND-tc/ros_mobile_robot_rsj_tutorial/"

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

exclude:
  - README.md
  - Gemfile

google_analytics: UA-99994866-1
